name: main

# run on pull requests and pushes to main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    outputs:
      build: ${{ steps.build.outputs.build }}
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 📦 Install Dependencies
        run: npm ci

      - name: ✨ Check Format
        run: npm run format:check

      - name: 🧹 Lint
        run: npm run lint

      - name: 👷 Build website
        run: npm run build

  # deploy to github pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🚀 Deploy to GitHub Pages
        uses: andstor/deploy-gh-pages@v2
        with:
          branch: gh-pages
          folder: build
          clean: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: 'Deploy to GitHub Pages'
      - name: 📝 Update README.md
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 Deployed to [GitHub Pages](https://andstor.github.io/andstor.github.io/)
